export const AUTH_REQUEST_START = "AUTH_REQUEST_START";
export const AUTH_REQUEST_SUCCESSFUL = "AUTH_REQUEST_SUCCESSFUL";
export const AUTH_REQUEST_FAILED = "AUTH_REQUEST_FAILED";


export const SIGN_UP_REQUEST_START = "SIGN_UP_REQUEST_START";
export const SIGN_UP_REQUEST_SUCCESSFUL = "SIGN_UP_REQUEST_SUCCESSFUL";
export const SIGN_UP_REQUEST_FAILED = "SIGN_UP_REQUEST_FAILED";


