export const POST_UPLOAD_REQUEST_START = "POST_UPLOAD_REQUEST_START";
export const POST_UPLOAD_REQUEST_SUCCESS = "POST_UPLOAD_REQUEST_SUCCESS";
export const POST_UPLOAD_REQUEST_FAILED = "POST_UPLOAD_REQUEST_FAILED";


