export const POST_UPLOAD_REQUEST_START = "POST_UPLOAD_REQUEST_START";
export const POST_UPLOAD_REQUEST_SUCCESS = "POST_UPLOAD_REQUEST_SUCCESS";
export const POST_UPLOAD_REQUEST_FAILED = "POST_UPLOAD_REQUEST_FAILED";

export const TIMELINE_POSTS_REQUEST = "TIMELINE_POSTS_REQUEST";
export const TIMELINE_POSTS_SUCCESS = "TIMELINE_POSTS_SUCCESS";
export const TIMELINE_POSTS_FAILED = "TIMELINE_POSTS_FAILED";
